// Generated by CoffeeScript 1.4.0
(function() {

  jQuery(function($) {
    return $("#main, #poupap_base, [data-group-cpf-cnpj]").on("click", "[data-group-cpf-cnpj-radio]", function() {
      var radio;
      radio = $(this);
      return radio.closest("[data-group-cpf-cnpj]").find(".input-prepend").find("i").attr("class", radio.attr("value") === "cpf" ? "icon-user" : "icon-briefcase").end().end().find("input:text").hide().prop("disabled", true).tooltip("destroy").filter("[data-" + radio.attr('value') + "]").show().prop("disabled", false).get(0).focus();
    });
  });

}).call(this);
